version: '3.8'

services:
  event-management-svc:
    build:
      context: ./event-management-svc
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
